# Most Common Resume Projects and their Advanced Version

| Sno  | Project                | Basic Version                          | Advanced Version                                                                                       | Resource Link                                     |
|----|------------------------|----------------------------------------|--------------------------------------------------------------------------------------------------------|---------------------------------------------------|
| 1  | Tic Tac Toe Game       | Basic Tic-Tac-Toe Game                | 🎖️ Multiplayer Tic-Tac-Toe using WebSockets                                                           | [WebSockets Tutorial](https://socket.io/)         |
| 2  | Weather Application    | Simple Weather App                    | 🎖️ Weather Bot for Discord with Alerts                                                               | [Discord.js Guide](https://discordjs.guide/)      |
| 3  | Ecommerce Website      | Basic Ecommerce Website               | 🎖️ AI-Driven Chrome Extension for Price Comparisons Using Web Scraping                                | [Puppeteer Docs](https://pptr.dev/)               |
| 4  | Crypto Tracker         | Static Crypto Tracker                 | 🎖️ AI-Powered Crypto Trading Bot                                                                      | [Binance API](https://www.binance.com/en/binance-api) |
| 5  | Portfolio Website      | Static Personal Portfolio Website     | 🎖️ Interactive Portfolio with Real-Time Analytics & AI Bot                                           | [ReactJS](https://reactjs.org/)                   |
| 6  | Calculator             | Simple Calculator                     | 🎖️ Advanced Financial Calculator with Tax, Loan, and Investment Features                              | [MDN Calculator Guide](https://developer.mozilla.org/en-US/) |
| 7  | To-Do List             | Basic To-Do App                       | 🎖️ Collaborative To-Do App with Task Dependencies and Deadlines                                      | [Firebase Docs](https://firebase.google.com/docs) |
| 8  | Blog Platform          | Simple Blog Platform                  | 🎖️ Dynamic Blog Platform with NLP-based Content Recommendations and Summaries                          | [TensorFlow.js](https://www.tensorflow.org/js)    |
| 9  | Social Media App       | Basic Social Media Platform           | 🎖️ Decentralized Social Media App with User-Curated Content Streams                                   | [Web3.js](https://web3js.readthedocs.io/)         |
| 10 | Language Translator    | Basic Language Translator             | 🎖️ AI-Powered Real-Time Voice Translator with Sentiment Analysis                                      | [Google Cloud Translate](https://cloud.google.com/translate/docs) |
| 11 | Task Management Tool   | Basic Task Manager                    | 🎖️ AI-Based Task Manager with Productivity Insights and Notifications                                 | [Microsoft AI API](https://azure.microsoft.com/en-us/products/cognitive-services/) |
| 12 | Fitness Tracker        | Simple Fitness Tracker                | 🎖️ AI-Powered Fitness Tracker with Workout Recommendations and Nutritional Analysis                   | [Nutritionix API](https://developer.nutritionix.com/) |
| 13 | Chatbot                | Basic Chatbot                         | 🎖️ AI Chatbot with Contextual Memory and Personalized Responses                                       | [Dialogflow](https://cloud.google.com/dialogflow) |
| 14 | Music Streaming App    | Simple Music Streaming App            | 🎖️ AI-Based Music Recommendation Platform with Mood Detection                                         | [Spotify API](https://developer.spotify.com/)     |
| 15 | Recipe Finder          | Simple Recipe Search                  | 🎖️ AI-Powered Recipe Finder with Dietary Preferences and Nutritional Analysis                         | [Spoonacular API](https://spoonacular.com/food-api) |
| 16 | Quiz App               | Basic Quiz Application                | 🎖️ Gamified Quiz App with Leaderboards and Interactive Feedback                                       | [Open Trivia Database](https://opentdb.com/)      |
| 17 | Video Streaming App    | Simple Video Streaming App            | 🎖️ AI-Based Video Summarization and Interactive Viewing Experience                                    | [Mux API](https://docs.mux.com/docs)              |
| 18 | Stock Market Tracker   | Basic Stock Market Tracking App       | 🎖️ Real-Time Stock Market Dashboard with Predictive Analytics                                         | [Alpha Vantage](https://www.alphavantage.co/)     |
| 19 | Virtual Classroom      | Basic Virtual Classroom App           | 🎖️ Interactive Classroom Platform with AI-Powered Participation Insights and Real-Time Feedback       | [BigBlueButton](https://bigbluebutton.org/)       |
| 20 | Travel Planner         | Simple Travel Itinerary App           | 🎖️ AI Travel Planner with Real-Time Location-Based Recommendations and Booking Integrations           | [Amadeus for Developers](https://developers.amadeus.com/) |
